### ISSUE TITLE
Alpha not working

### ISSUE THREAD

**Issue by jmraker** [MrSprigster/Twitch.tv-on-XBMC#626]
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.6.0-alpha1
* Kodi Version: leia
* Kodi GUI Language: English
* Operating System: LibreElec 9.2 on Raspberry 3 hooked up to a TV
* Operating System Language: English

------

I downloaded the 2 zip files and installed them from the zip files and rebooted.
The addon now shows 3 items on the initial menu.
Trying to browse games (first option) brings a notification that it found no games.

I came back a while later and did the steps to get an oauth token.  Instead of typing them via a remote I opted to edit "settings.xml" over ssh. 
Edited the line with "<setting id="private_oauth_token">ImagineMyTokenWasPastedHere</setting>"
I rebooted and nothing changed.  I can see the token is set in the settings.

I then tried to go back to the working addons.  Didn't work until I restored settings.xml back, so I'm back on v5 and may try installing it and doing the oauth thing again.

------

2022-02-16 14:19:32.274 T:1937519664  NOTICE: ADDON: plugin.video.twitch v2.6.0~alpha1 installed
2022-02-16 14:19:32.277 T:1937519664  NOTICE: ADDON: script.module.python.twitch v2.0.21~alpha1 installed

2022-02-16 18:40:56.477 T:1356571520   ERROR: GetDirectory - Error getting plugin://plugin.video.twitch/?mode=games
2022-02-16 18:40:56.478 T:1937691696   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/?mode=games) failed

2022-02-16 18:53:56.238 T:1709331328   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named v5
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/service_runner.py", line 12, in <module>
                                                from twitch_addon import service
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/service.py", line 21, in <module>
                                                from .addon.constants import Keys
                                              File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/constants.py", line 14, in <module>
                                                from twitch.oauth.v5 import scopes
                                            ImportError: No module named v5
                                            -->End of Python script error report<--

2022-02-16 18:54:36.795 T:1486599040  NOTICE: ADDON: plugin.video.twitch v2.5.12 installed
2022-02-16 18:54:30.841 T:1535406976  NOTICE: ADDON: script.module.python.twitch v2.0.19 installed

2022-02-16 18:54:37.307 T:1510228864 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by anxdpanic** [comment]
Likely an issue with the installation itself, 

> File "/storage/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/constants.py", line 14, in
from twitch.oauth.v5 import scopes
ImportError: No module named v5

https://github.com/anxdpanic/plugin.video.twitch/blob/master/resources/lib/twitch_addon/addon/constants.py#L14

You can see above the line doesn't match the current version
