### ISSUE TITLE
Clips not working if Game Title is included in the "Display titles" setting

### ISSUE THREAD

**Issue by apo86** [MrSprigster/Twitch.tv-on-XBMC#630]
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.6.0.beta1
* Kodi Version: 19.3
* Kodi GUI Language: en
* Operating System: osmc
* Operating System Language: en

------

### Expected Behavior

Clips working regardless of "Display titles" setting

------

### Current Behavior

Clip list is not shown if Game Title is included in the selection for Display titles. Getting an error instead

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to Settings -> General -> Display titles
2. Select one of the template options that include the Game Title, like "Streamer - Game Title - Stream Title"
3. Go to Following -> Channels -> pick a random channel -> Clips

------

### Log

2022-02-17 19:37:56.103 T:4228    DEBUG <general>: Twitch: Version: |2.6.0~beta1+matrix.1| Application Version: |Kodi| |19.3| -> |19|3||0||
2022-02-17 19:37:56.103 T:4228    DEBUG <general>: Twitch: Queries: |{'mode': 'clips_list', 'channel_id': '57025612'}| Args: |['plugin://plugin.video.twitch/', '39', '?channel_id=57025612&game_id&mode=clips_list', 'resume:false']|
2022-02-17 19:37:56.104 T:4228    DEBUG <general>: Twitch: Using method cache for: |twitch_addon.addon.api.Twitch.valid_token| -> |4|
2022-02-17 19:37:56.104 T:4228     INFO <general>: Twitch: Calling |_list_clips| for mode |clips_list| with pos args |[]| and kwargs |{'channel_id': '57025612'}|
2022-02-17 19:37:56.107 T:4228    DEBUG <general>: Twitch: Calling cached method: |twitch_addon.addon.api.Twitch.get_clips|
2022-02-17 19:37:56.119 T:4228    DEBUG <general>: script.module.python.twitch: GET QUERY: url: |https://api.twitch.tv/helix/clips|, params: |[('first', 25), ('broadcaster_id', '57025612')]|, data: |{}|, headers: |{'Client-ID': 'ps2ed9zlj8zyqztsdz2tl4uys84b8k', 'Authorization': 'Bearer ***********'}|, target_func: |get_clip|
2022-02-17 19:37:56.120 T:4228    DEBUG <general>: script.module.python.twitch: Downloading: |https://api.twitch.tv/helix/clips?first=25&broadcaster_id=57025612|
2022-02-17 19:37:56.180 T:2713    DEBUG <general>: PushCecKeypress - received key  b duration 126
2022-02-17 19:37:56.181 T:2656    DEBUG <general>: ------ Window Init (DialogBusy.xml) ------
2022-02-17 19:37:56.767 T:4228    DEBUG <general>: script.module.python.twitch: url: |https://api.twitch.tv/helix/clips| parameters: |[('first', 25), ('broadcaster_id', '57025612')]|
                                                   {
                                                       "data": [
                                                           {
                                                               "broadcaster_id": "57025612",
                                                               "broadcaster_name": "Thijs",
                                                               "created_at": "2016-09-13T13:50:20Z",
                                                               "creator_id": "52294942",
                                                               "creator_name": "bbdejom",
                                                               "duration": 32,
                                                               "embed_url": "https://clips.twitch.tv/embed?clip=WittyPrettiestTildePJSugar",
                                                               "game_id": "138585",
                                                               "id": "WittyPrettiestTildePJSugar",
                                                               "language": "nl",
                                                               "thumbnail_url": "https://clips-media-assets2.twitch.tv/23155213088-offset-21202-preview-480x272.jpg",
                                                               "title": "G2.Thijs - High Legend Malygos Warlock.",
                                                               "url": "https://clips.twitch.tv/WittyPrettiestTildePJSugar",
                                                               "video_id": "",
                                                               "view_count": 357309
                                                           },
[...]
                                                       ],
                                                       "pagination": {
                                                           "cursor": "eyJiIjpudWxsLCJhIjp7IkN1cnNvciI6Ik1qVT0ifX0"
                                                       }
                                                   }
2022-02-17 19:37:56.781 T:4228    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'game'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/addon_runner.py", line 15, in <module>
                                                       router.run(sys.argv)
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 297, in run
                                                       dispatcher.dispatch(mode, queries)
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/common/url_dispatcher.py", line 94, in dispatch
                                                       self.func_registry[mode](*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/error_handling.py", line 32, in wrapper
                                                       result = func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 129, in _list_clips
                                                       clips.route(twitch_api, after, channel_id, game_id)
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/routes/clips.py", line 33, in route
                                                       kodi.create_item(converter.clip_to_listitem(clip))
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/converter.py", line 130, in clip_to_listitem
                                                       return {'label': self.get_title_for_clip(clip),
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/converter.py", line 315, in get_title_for_clip
                                                       return self.title_builder.format_title(title_values)
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/utils.py", line 534, in format_title
                                                       title = template.format(**title_values)
                                                   KeyError: 'game'
                                                   -->End of Python script error report<--

------

### Additional Information

The API doesn't return a game title anymore. It does provide a game_id, which I can't believe Twitch doesn't provide a translation API for??? But I can't find one, so...
I guess the easiest way to deal with it would be to replace the game name by "unknown game" if it is not available.

------

**Comment by anxdpanic** [comment]
I fixed the crash by adding unknown game in beta2. I will look into fixing the title builder / game name issue separately in the the future

**Comment by apo86** [comment]
Thanks!
