### ISSUE TITLE
Search stream not working if Viewers is included in the "Display titles" setting

### ISSUE THREAD

**Issue by apo86** [MrSprigster/Twitch.tv-on-XBMC#637]
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.6.0.beta4
* Kodi Version: 19.3
* Kodi GUI Language: en
* Operating System: osmc
* Operating System Language: en

------

### Expected Behavior

Search working

------

### Current Behavior

Error when Viewers # is included in the Display titles setting

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to Settings -> General -> Display titles
2. Select one of the template options that include Viewers, like "Viewers - Streamer - Stream Title"
3. Go to Search -> Streams -> search for anything

------

### Log

2022-02-18 20:31:36.749 T:6425    DEBUG <general>: script.module.python.twitch: url: |https://api.twitch.tv/helix/search/channels| parameters: |[('query', 'lirik'), ('first', 25), ('live_only', 'true')]|
                                                   {
                                                       "data": [
                                                           {
                                                               "broadcaster_language": "en",
                                                               "broadcaster_login": "lirik",
                                                               "display_name": "LIRIK",
                                                               "game_id": "518015",
                                                               "game_name": "Horizon Forbidden West",
                                                               "id": "23161357",
                                                               "is_live": true,
                                                               "started_at": "2022-02-18T17:03:19Z",
                                                               "tag_ids": [
                                                                   "c2839af5-f1d2-46c4-8edc-1d0bfbd85070",
                                                                   "6ea6bca4-4712-4ab9-a906-e3336a9d8039"
                                                               ],
                                                               "thumbnail_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/27fdad08-a2c2-4e0b-8983-448c39519643-profile_image-300x300.png",
                                                               "title": "Horizon: Forbidden Pepega - MSQ FOCUS"
                                                           },
                                                           {
                                                               "broadcaster_language": "es",
                                                               "broadcaster_login": "liriacea",
                                                               "display_name": "Liriacea",
                                                               "game_id": "68018",
                                                               "game_name": "Elsword",
                                                               "id": "590452238",
                                                               "is_live": true,
                                                               "started_at": "2022-02-18T19:01:01Z",
                                                               "tag_ids": [
                                                                   "52d7e4cc-633d-46f5-818c-bb59102d9549",
                                                                   "6606e54c-f92d-40f6-8257-74977889ccdd",
                                                                   "8ba227ca-073c-46a7-b3cc-193e52c5ab4d",
                                                                   "d4bb9c58-2141-4881-bcdc-3fe0505457d1"
                                                               ],
                                                               "thumbnail_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/3642fd21-fdad-4a22-a34e-5a758087c339-profile_image-300x300.png",
                                                               "title": "\u300e Elsword NA \u300f Personajes nuevos aaaa (\u0e51\u2727\u25e1\u2727\u0e51)"
                                                           }
                                                       ],
                                                       "pagination": {}
                                                   }
2022-02-18 20:31:36.780 T:6425    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'viewers'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/addon_runner.py", line 15, in <module>
                                                       router.run(sys.argv)
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 297, in run
                                                       dispatcher.dispatch(mode, queries)
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/common/url_dispatcher.py", line 94, in dispatch
                                                       self.func_registry[mode](*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/error_handling.py", line 32, in wrapper
                                                       result = func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 66, in _search_results
                                                       search_results.route(twitch_api, content, query, after)
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/routes/search_results.py", line 41, in route
                                                       kodi.create_item(converter.search_stream_to_listitem(stream))
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/converter.py", line 172, in search_stream_to_listitem
                                                       title = self.get_title_for_search(search)
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/converter.py", line 338, in get_title_for_search
                                                       return self.title_builder.format_title(title_values)
                                                     File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/utils.py", line 534, in format_title
                                                       title = template.format(**title_values)
                                                   KeyError: 'viewers'
                                                   -->End of Python script error report<--

------

### Additional Information

This is similar to #630 
Number of viewers is no longer included in search results, but the addon has no fallback defined if it's missing

------

**Comment by anxdpanic** [comment]
fixed in beta5

**Comment by apo86** [comment]
Thanks!
