### ISSUE TITLE
Unable to play any stream

### ISSUE THREAD

**Issue by fearlesschicken** [MrSprigster/Twitch.tv-on-XBMC#681]
### Context

Please provide any relevant information about your setup

* Add-on Version: 3.0.1
* Kodi Version: 20.1
* Kodi GUI Language: EN-US
* Operating System: MacOS Monterey
* Operating System Language: EN-US

------

### Expected Behavior

Please describe the behavior you are expecting.

Play a twitch stream

------

### Current Behavior

What is the current behavior?

Errors out

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Attempt to play a stream

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

2023-05-31 16:39:23.228 T:3223814    info <general>: Twitch: Calling |_play| for mode |play| with pos args |[]| and kwargs |{'channel_id': '20687650'}|
2023-05-31 16:39:23.518 T:3223814   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: list indices must be integers or slices, not str
                                                   Traceback (most recent call last):
                                                     File "/Users/asdfl/Library/Application Support/Kodi/addons/plugin.video.twitch/resources/lib/addon_runner.py", line 15, in <module>
                                                       router.run(sys.argv)
                                                     File "/Users/asdfl/Library/Application Support/Kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 297, in run
                                                       dispatcher.dispatch(mode, queries)
                                                     File "/Users/asdfl/Library/Application Support/Kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/common/url_dispatcher.py", line 94, in dispatch
                                                       self.func_registry[mode](*args, **kwargs)
                                                     File "/Users/asdfl/Library/Application Support/Kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/error_handling.py", line 30, in wrapper
                                                       result = func(*args, **kwargs)
                                                                ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Users/asdfl/Library/Application Support/Kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/router.py", line 157, in _play
                                                       play.route(twitch_api, seek_time, channel_id, video_id, slug, ask, use_player, quality, channel_name)
                                                     File "/Users/asdfl/Library/Application Support/Kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/routes/play.py", line 133, in route
                                                       videos = api.get_live(name)
                                                                ^^^^^^^^^^^^^^^^^^
                                                     File "/Users/asdfl/Library/Application Support/Kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/error_handling.py", line 72, in wrapper
                                                       result = func(*args, **kwargs)
                                                                ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Users/asdfl/Library/Application Support/Kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/common/cache.py", line 103, in memoizer
                                                       result = func(*args, **kwargs)
                                                                ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Users/asdfl/Library/Application Support/Kodi/addons/plugin.video.twitch/resources/lib/twitch_addon/addon/api.py", line 346, in get_live
                                                       results = self.usher.live(name, headers=self.get_private_credential_headers())
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Users/asdfl/Library/Application Support/Kodi/addons/script.module.python.twitch/resources/lib/twitch/parser.py", line 51, in m3u8_wrapper
                                                       results = f(*args, **kwargs)
                                                                 ^^^^^^^^^^^^^^^^^^
                                                     File "/Users/asdfl/Library/Application Support/Kodi/addons/script.module.python.twitch/resources/lib/twitch/api/usher.py", line 154, in live
                                                       return _live(channel, token, headers=headers)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Users/asdfl/Library/Application Support/Kodi/addons/script.module.python.twitch/resources/lib/twitch/queries.py", line 255, in wrapper
                                                       qry = f(*args, **kwargs)
                                                             ^^^^^^^^^^^^^^^^^^
                                                     File "/Users/asdfl/Library/Application Support/Kodi/addons/script.module.python.twitch/resources/lib/twitch/api/usher.py", line 126, in _live
                                                       signature = token[keys.SIGNATURE]
                                                                   ~~~~~^^^^^^^^^^^^^^^^
                                                   TypeError: list indices must be integers or slices, not str
                                                   -->End of Python script error report<--
                                                   
2023-05-31 16:39:23.567 T:3216024   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?mode=play&channel_id=20687650]


[kodi-twitch-debug.log](https://github.com/anxdpanic/plugin.video.twitch/files/11619627/kodi-twitch-debug.log)


I have tried a changing my token to no avail.  Debug mode log attached.

**Comment by Cnuut** [comment]
https://github.com/streamlink/streamlink/issues/5370

**Comment by fearlesschicken** [comment]
Close due to dupe issue
https://github.com/anxdpanic/plugin.video.twitch/issues/682
